param(
    [string]$RepoRoot = $PSScriptRoot,
    [string]$SdkDir = "",
    [switch]$EnableChinaMirrors
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-Text([string]$Path) {
    return Get-Content -LiteralPath $Path -Raw -Encoding UTF8
}

function Set-Text([string]$Path, [string]$Content) {
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

$changes = New-Object System.Collections.Generic.List[string]

# 1) Gradle Wrapper: mirror + timeout
$wrapperPath = Join-Path $RepoRoot "gradle\wrapper\gradle-wrapper.properties"
if (-not (Test-Path -LiteralPath $wrapperPath)) {
    throw "Not found: $wrapperPath"
}

$wrapperText = Get-Text $wrapperPath
$newWrapperText = $wrapperText `
    -replace '(?m)^distributionUrl=.*$', 'distributionUrl=https\://mirrors.cloud.tencent.com/gradle/gradle-9.4.1-bin.zip'

if ($newWrapperText -match '(?m)^networkTimeout=') {
    $newWrapperText = $newWrapperText -replace '(?m)^networkTimeout=.*$', 'networkTimeout=120000'
} else {
    $newWrapperText = $newWrapperText.TrimEnd() + "`r`nnetworkTimeout=120000`r`n"
}

if ($newWrapperText -ne $wrapperText) {
    Set-Text $wrapperPath $newWrapperText
    $changes.Add("gradle/wrapper/gradle-wrapper.properties")
}

# 2) settings.gradle.kts: optional mirrors + safe GitHub Packages credentials
$settingsPath = Join-Path $RepoRoot "settings.gradle.kts"
if (-not (Test-Path -LiteralPath $settingsPath)) {
    throw "Not found: $settingsPath"
}

$settingsText = Get-Text $settingsPath
$newSettingsText = $settingsText

# Enable mirror lines only when explicitly requested.
if ($EnableChinaMirrors) {
    $newSettingsText = $newSettingsText -replace '(?m)^(\s*)//\s*maven \{ setUrl\("https://maven\.aliyun\.com/repository/public/"\) \}\s*$', '$1maven { setUrl("https://maven.aliyun.com/repository/public/") }'
    $newSettingsText = $newSettingsText -replace '(?m)^(\s*)//\s*maven \{ setUrl\("https://repo\.huaweicloud\.com/repository/maven/"\) \}\s*$', '$1maven { setUrl("https://repo.huaweicloud.com/repository/maven/") }'
}

$guardedBlock = @'
        val gprUser = providers.gradleProperty("gpr.user")
            .orElse(providers.environmentVariable("GITHUB_ACTOR"))
            .getOrElse("")
        val gprKey = providers.gradleProperty("gpr.key")
            .orElse(providers.environmentVariable("GITHUB_TOKEN"))
            .getOrElse("")
        if (gprUser.isNotBlank() && gprKey.isNotBlank()) {
            maven {
                url = uri("https://maven.pkg.github.com/compose-miuix-ui/miuix")
                credentials {
                    username = gprUser
                    password = gprKey
                }
            }
        }
'@

# Replace old unsafe getenv/get() block
$unsafeBlock = '(?s)maven\s*\{\s*url\s*=\s*uri\("https://maven\.pkg\.github\.com/compose-miuix-ui/miuix"\)\s*credentials\s*\{\s*username\s*=\s*providers\.gradleProperty\("gpr\.user"\)\s*\.orElse\(System\.getenv\("GITHUB_ACTOR"\)\)\s*\.get\(\)\s*password\s*=\s*providers\.gradleProperty\("gpr\.key"\)\s*\.orElse\(System\.getenv\("GITHUB_TOKEN"\)\)\s*\.get\(\)\s*\}\s*\}'
$newSettingsText = [regex]::Replace($newSettingsText, $unsafeBlock, $guardedBlock)

# If still no guarded variables, replace generic GitHub Packages maven block once
if ($newSettingsText -notmatch 'val\s+gprUser\s*=\s*providers\.gradleProperty\("gpr\.user"\)') {
    $genericGithubMavenBlock = '(?s)maven\s*\{\s*url\s*=\s*uri\("https://maven\.pkg\.github\.com/compose-miuix-ui/miuix"\)\s*credentials\s*\{.*?\}\s*\}'
    $newSettingsText = [regex]::Replace($newSettingsText, $genericGithubMavenBlock, $guardedBlock, 1)
}

if ($newSettingsText -ne $settingsText) {
    Set-Text $settingsPath $newSettingsText
    $changes.Add("settings.gradle.kts")
}

# 3) local.properties: ensure sdk.dir exists
if ([string]::IsNullOrWhiteSpace($SdkDir)) {
    if (-not [string]::IsNullOrWhiteSpace($env:ANDROID_SDK_ROOT)) {
        $SdkDir = $env:ANDROID_SDK_ROOT
    } elseif (-not [string]::IsNullOrWhiteSpace($env:ANDROID_HOME)) {
        $SdkDir = $env:ANDROID_HOME
    } else {
        $SdkDir = Join-Path $env:LOCALAPPDATA "Android\Sdk"
    }
}

$localPropsPath = Join-Path $RepoRoot "local.properties"
$escapedSdkDir = $SdkDir -replace '\\', '\\'
$localPropsText = "## This file is generated by apply-local-fix.ps1.`r`nsdk.dir=$escapedSdkDir`r`n"

$writeLocalProps = $true
if (Test-Path -LiteralPath $localPropsPath) {
    $existingLocalPropsText = Get-Text $localPropsPath
    if ($existingLocalPropsText -eq $localPropsText) {
        $writeLocalProps = $false
    }
}

if ($writeLocalProps) {
    Set-Text $localPropsPath $localPropsText
    $changes.Add("local.properties")
}

if ($changes.Count -eq 0) {
    Write-Output "No local fixes were needed."
} else {
    Write-Output "Applied local fixes:"
    $changes | ForEach-Object { Write-Output (" - " + $_) }
}

if (-not (Test-Path -LiteralPath $SdkDir)) {
    Write-Warning "SDK directory does not exist: $SdkDir"
}

# 4) Preflight warning for GitHub Packages SNAPSHOT dependencies
$libsTomlPath = Join-Path $RepoRoot "gradle\libs.versions.toml"
if (Test-Path -LiteralPath $libsTomlPath) {
    $libsTomlText = Get-Text $libsTomlPath
    $usesMiuixSnapshot = $libsTomlText -match '(?m)^\s*miuix\s*=\s*".*SNAPSHOT.*"\s*$'
    if ($usesMiuixSnapshot) {
        $userGradlePropsPath = Join-Path $env:USERPROFILE ".gradle\gradle.properties"
        $hasGprUser = $false
        $hasGprKey = $false

        if (Test-Path -LiteralPath $userGradlePropsPath) {
            $userGradlePropsText = Get-Text $userGradlePropsPath
            $hasGprUser = $userGradlePropsText -match '(?m)^\s*gpr\.user\s*=\s*\S+\s*$'
            $hasGprKey = $userGradlePropsText -match '(?m)^\s*gpr\.key\s*=\s*\S+\s*$'
        }

        if ([string]::IsNullOrWhiteSpace($env:GITHUB_ACTOR) -eq $false) {
            $hasGprUser = $true
        }
        if ([string]::IsNullOrWhiteSpace($env:GITHUB_TOKEN) -eq $false) {
            $hasGprKey = $true
        }

        if (-not ($hasGprUser -and $hasGprKey)) {
            Write-Warning @"
Detected SNAPSHOT miuix dependency in gradle/libs.versions.toml, but GitHub Packages credentials were not found.
Set one of the following before build:
  1) ~/.gradle/gradle.properties:
     gpr.user=<your_github_username>
     gpr.key=<github_pat_with_read_packages>
  2) Environment variables:
     GITHUB_ACTOR / GITHUB_TOKEN
"@
        }
    }
}
